//AULA_ID
//PROF_ID
//TOKEN
//USUARIO


//-----------------------------------


//SOLUÇÃO

//PROFESSOR - TOKEN - TB_AULA - GRAVAÇÃO A GENTE GARANTE QUE SÓ O PROFESSOR VAI PODER GERAR O TOKEN, VALIDAR PARA OUTROS PROFESSORES NÃO GERAREM DE OUTRAS AULAS
//ALUNO - CRIPTOGRAFAR TUDO - CRIAR TOKEN DE ALUNO/AULA


//DOIS PROBLEMA:
// 1- COMPARTILHAR QR CODE COM AMIGUINHO
// 2- LOGAR NO CELULAR NO COLUGA


//-----------------------------------